add_newline = true
scan_timeout = 10

[character]
success_symbol = "[➜](bold green)"
error_symbol = "[✗](bold red)"

[directory]
truncation_length = 0
truncate_to_repo = false

[git_status]
disabled = false
ignore_submodules = true
